version: 1.0.{build}
image: Visual Studio 2017
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
- ps: >-
    nuget restore

    nuGet pack NBitcoin.Indexer\NBitcoin.Indexer.csproj -Build -Properties Configuration=Release -includereferencedprojects
build:
  verbosity: minimal
after_build:
- ps: 7z a NBitcoin.Indexer.Console.zip $env:APPVEYOR_BUILD_FOLDER\NBitcoin.Indexer.Console\bin
test: off
artifacts:
- path: '*.nupkg'
deploy:
- provider: NuGet
  api_key:
    secure: Vj1/ff4lsgejgj4i8s5CFyqVeLmBSmVqnw9iz/rQBILnX7IigQ8cP/JqgQTrIgje
